ARCHITECTURE = avr
BOARD_TAG   = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_DIR = /home/pi/arduino-1.8.2
ARDUINO_AVR = $(ARDUINO_DIR)/hardware/arduino/avr
BOARDS_TXT = $(ARDUINO_AVR)/boards.txt
ARDUINO_CORE_PATH = $(ARDUINO_AVR)/cores/arduino
ARDUINO_VAR_PATH = $(ARDUINO_AVR)/variants
ARDUINO_SKETCHBOOK = /home/pi/Arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
include /usr/share/arduino/Arduino.mk

